### ISSUE TITLE
Add Favicon to website

### ISSUE THREAD

**Issue by lupyana** [pythontanzania/djangogirlstz#15]
# Add Favicon to Website

## Description
We need to add a favicon to our website to improve brand recognition and enhance the user experience. The favicon will appear in browser tabs, bookmarks, and other places where the site is referenced.

## Current State
The website currently does not have a favicon.

## Tasks
- [ ] Use logo to generate favicons
  - Should be recognizable at small sizes (16x16, 32x32 pixels)
  - Should reflect our brand (e.g., use our logo or a simplified version of it)
- [ ] Create favicon files in multiple sizes:
  - 16x16 pixels
  - 32x32 pixels
  - 48x48 pixels
  - 64x64 pixels
- [ ] Generate favicon files in different formats:
  - .ico (for older browsers)
  - .png (for modern browsers)
  - Apple Touch Icon (for iOS devices)
- [ ] Add appropriate HTML tags to the `<head>` section of our website:

```html
<link rel="icon" type="image/x-icon" href="/path/to/favicon.ico">
<link rel="icon" type="image/png" sizes="32x32" href="/path/to/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/path/to/favicon-16x16.png">
<link rel="apple-touch-icon" sizes="180x180" href="/path/to/apple-touch-icon.png">
```
![Django Girls](https://github.com/user-attachments/assets/aa75ad58-9fde-42a9-960b-260c9f5df82b)

**Comment by SABRINAmsuya** [comment]
Okay, On it.

**Comment by lupyana** [comment]
@SABRINAmsuya kindly make sure that you start from the main branch with the latest changes, before starting your work.
I have closed the prevous PR without mergins since your branch was behind. 

You will need to redo this isssue

**Comment by SABRINAmsuya** [comment]
Okay, I'm doing that now.
